app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

#REST
api:
    type:     rest
    resource: AppBundle\Controller\ApiController